INSERT INTO Z_RAF_EXAMEN (DESCRIPCION) SELECT DISTINCT r.EXAMEN AS DESCRIPCION FROM Z_RAF_HISTORICO_LMS r

INSERT INTO [FLUIG_DESA].[dbo].[Z_RAF_HISTORICO_LMS] ([MATRICULA],[LOGIN],[APELLIDO],[NOMBRE],[EMAIL],[EXAMEN],[FINAL_STATUS], PUNTAJE, FECHA) 
SELECT [ut].[USER_CODE] AS MATRICULA, [ut].[LOGIN], [u].[LAST_NAME] AS APELLIDO, [u].[FIRST_NAME] AS NOMBRE, [ut].[EMAIL],  [sti].[STRING_VALUE] AS EXAMEN, [e].[FINAL_STATUS], [e].[SCORE_POS_EXAM] AS PUNTAJE, DATEADD(s,[e].[CONCLUSION_TIMESTAMP]/1000,'19700101') AS FECHA 
FROM [dbo].[ELE_PARTY] p,  [dbo].[FDN_USER] u, [dbo].[FDN_USERTENANT] ut, [dbo].[ELE_ENROLLMENT] e, [dbo].[ELE_ENROLLMENT_REQUEST] er, 
[dbo].[ELE_ENRLLBL_ITM_ASSMNT_APPLCTN] aa,  [dbo].[ELE_CATALOG_ENROLLABLE_ITEM] cei, [dbo].[ELE_CATALOG_NORMAL_ITEM] cni, [dbo].[ELE_SHORT_TRANSLATE_ITEM] sti
WHERE [p].[ID_FLUIG] = [u].[USER_ID] AND [ut].[USER_ID] = [u].[USER_ID] AND [er].[ID] = [e].[ID_ENROLLMENT_REQUEST] AND [er].[ID_USER] = [p].[ID] AND [aa].[ID_ENROLLMENT] = [e].[ID]
AND [aa].[ID_ENROLLABLE_ITEM] = [cei].[ID] AND [cni].[ID] = [aa].[ID_ENROLLABLE_ITEM] AND [cni].[NAME_ID] = [sti].[ID] AND [e].[FINAL_STATUS] <> 'CANCELLED'
ORDER BY  [u].[LAST_NAME],[u].[FIRST_NAME], [aa].[ID_ENROLLABLE_ITEM];