EXEC sp_RENAME '[dbo].[Z_RAF_EMPLEADO].nombre' , 'nombreCompleto', 'COLUMN'

ALTER TABLE [dbo].[Z_RAF_EMPLEADO]
ADD nombre VARCHAR(1000);

ALTER TABLE [dbo].[Z_RAF_EMPLEADO]
ADD apellido VARCHAR(1000);

ALTER TABLE [dbo].[Z_RAF_EMPLEADO]
ADD tipoDocumento VARCHAR(1000);

ALTER TABLE [dbo].[Z_RAF_EMPLEADO]
ADD nroDocumento VARCHAR(1000);

ALTER TABLE [dbo].[Z_RAF_EMPLEADO]
ADD cuil VARCHAR(1000);

ALTER TABLE [dbo].[Z_RAF_EMPLEADO]
ADD fechaNacimiento VARCHAR(1000);

ALTER TABLE [dbo].[Z_RAF_EMPLEADO]
ADD genero VARCHAR(1000);

ALTER TABLE [dbo].[Z_RAF_EMPLEADO]
ADD estadoCivil VARCHAR(1000);

ALTER TABLE [dbo].[Z_RAF_EMPLEADO]
ADD nacionalidad VARCHAR(1000);

ALTER TABLE [dbo].[Z_RAF_EMPLEADO]
ADD empresa VARCHAR(1000);

ALTER TABLE [dbo].[Z_RAF_EMPLEADO]
ADD lugarPago VARCHAR(1000);

ALTER TABLE [dbo].[Z_RAF_EMPLEADO]
ADD domicilio VARCHAR(1000);

UPDATE [dbo].[DOCUMENTO]
SET [NUM_VERS_PROPRIED]=3000
WHERE [NR_DOCUMENTO] IN (SELECT DISTINCT [documentid] FROM [dbo].[ML001034])