ALTER TABLE Z_RAF_INVERSION_COMERCIAL ADD CONGRESO_ID INT;
--ALTER TABLE Z_RAF_INVERSION_COMERCIAL ADD MEMBRESIA VARCHAR(2);
ALTER TABLE Z_RAF_INVERSION_COMERCIAL ADD COMENTARIOS_ALOJAMIENTO VARCHAR (4000);
--ALTER TABLE Z_RAF_INVERSION_COMERCIAL ADD DIAS_REQUERIDOS INT;
ALTER TABLE Z_RAF_INVERSION_COMERCIAL ADD NOMBRE_MEDICO_1 VARCHAR (255);
ALTER TABLE Z_RAF_INVERSION_COMERCIAL ADD NOMBRE_MEDICO_2 VARCHAR (255);
ALTER TABLE Z_RAF_INVERSION_COMERCIAL ADD COMPARTE_HABITACION VARCHAR (2);
ALTER TABLE Z_RAF_INVERSION_COMERCIAL ADD COMENTARIOS_IDA VARCHAR (4000);
ALTER TABLE Z_RAF_INVERSION_COMERCIAL ADD COMENTARIOS_REGRESO VARCHAR (4000);
ALTER TABLE Z_RAF_INVERSION_COMERCIAL ADD TIPO_TRASLADO_IDA VARCHAR(10);
ALTER TABLE Z_RAF_INVERSION_COMERCIAL ADD TIPO_TRASLADO_REGRESO VARCHAR(10);
ALTER TABLE Z_RAF_INVERSION_COMERCIAL ADD CUIT VARCHAR(20);
ALTER TABLE Z_RAF_INVERSION_COMERCIAL ADD DIAS_LIMITE_CARGA INT;
ALTER TABLE Z_RAF_INVERSION_COMERCIAL ADD PRESUPUESTO_HABILITADO VARCHAR(255);
ALTER TABLE Z_RAF_INVERSION_COMERCIAL ADD INCLUYE_ALOJAMIENTO VARCHAR(2);
ALTER TABLE Z_RAF_INVERSION_COMERCIAL ADD INCLUYE_TRASLADO VARCHAR(2);
ALTER TABLE Z_RAF_INVERSION_COMERCIAL ADD INCLUYE_INSCRIPCION VARCHAR(2);
ALTER TABLE Z_RAF_INVERSION_COMERCIAL ADD SELECCION_ALOJAMIENTO_PRESUPUESTO VARCHAR(255);
ALTER TABLE Z_RAF_INVERSION_COMERCIAL ADD SELECCION_TRASLADO_PRESUPUESTO VARCHAR(255);
ALTER TABLE Z_RAF_INVERSION_COMERCIAL ADD SELECCION_INSCRIPCION_PRESUPUESTO VARCHAR(255);
ALTER TABLE Z_RAF_INVERSION_COMERCIAL ADD COMENTARIOS_CONGRESO VARCHAR (4000);
ALTER TABLE Z_RAF_INVERSION_COMERCIAL ADD CARTA_PETITORIO_ARCHIVO VARCHAR (1000);
ALTER TABLE Z_RAF_INVERSION_COMERCIAL ADD CARTA_PETITORIO_DOC_ID VARCHAR (255);
ALTER TABLE Z_RAF_INVERSION_COMERCIAL ADD CARTA_ACUERDO_ARCHIVO VARCHAR (1000);
ALTER TABLE Z_RAF_INVERSION_COMERCIAL ADD CARTA_ACUERDO_DOC_ID VARCHAR (255);
ALTER TABLE Z_RAF_INVERSION_COMERCIAL ADD FLYER_ARCHIVO VARCHAR (1000);
ALTER TABLE Z_RAF_INVERSION_COMERCIAL ADD FLYER_DOC_ID VARCHAR (255);
ALTER TABLE Z_RAF_INVERSION_COMERCIAL ADD WEB VARCHAR (4000);
ALTER TABLE Z_RAF_INVERSION_COMERCIAL ADD MES_INVERSION DATE;
ALTER TABLE Z_RAF_INVERSION_COMERCIAL ADD DELEGADO bit;
ALTER TABLE Z_RAF_INVERSION_COMERCIAL ADD MONTO_INVERSION NUMERIC(18,2);
ALTER TABLE Z_RAF_INVERSION_COMERCIAL ADD CONTACTO_MEDICO_1 VARCHAR (255);
ALTER TABLE Z_RAF_INVERSION_COMERCIAL ADD CONTACTO_MEDICO_2 VARCHAR (255);

ALTER TABLE Z_RAF_CARTA_ACUERDO ADD COMENTARIOS_CONGRESO VARCHAR (4000);
ALTER TABLE Z_RAF_CARTA_ACUERDO ADD CARTA_PETITORIO_ARCHIVO VARCHAR (1000);
ALTER TABLE Z_RAF_CARTA_ACUERDO ADD CARTA_PETITORIO_DOC_ID VARCHAR (255);
ALTER TABLE Z_RAF_CARTA_ACUERDO ADD CARTA_ACUERDO_ARCHIVO VARCHAR (1000);
ALTER TABLE Z_RAF_CARTA_ACUERDO ADD CARTA_ACUERDO_DOC_ID VARCHAR (255);
ALTER TABLE Z_RAF_CARTA_ACUERDO ADD FLYER_ARCHIVO VARCHAR (1000);
ALTER TABLE Z_RAF_CARTA_ACUERDO ADD FLYER_DOC_ID VARCHAR (255);
ALTER TABLE Z_RAF_CARTA_ACUERDO ADD NOMBRE_CONGRESO VARCHAR (255);
ALTER TABLE Z_RAF_CARTA_ACUERDO ADD WEB VARCHAR (4000);
ALTER TABLE Z_RAF_CARTA_ACUERDO ADD FECHA_FIN_SOLICITUD DATE;
ALTER TABLE Z_RAF_CARTA_ACUERDO ADD DELEGADO bit;


ALTER TABLE Z_RAF_MEDICO ADD CIUDAD VARCHAR (50);

ALTER TABLE Z_RAF_CONGRESO ADD CODIGO VARCHAR (9) null;

--Sólo para desarrollo
ALTER TABLE Z_RAF_CONGRESO ADD CONSTRAINT UK_Z_RAF_CONGRESO_CODIGO UNIQUE (CODIGO); 


