ALTER TABLE Z_RAF_CARTA_ACUERDO ADD INCLUYE_ALOJAMIENTO VARCHAR (255);
ALTER TABLE Z_RAF_CARTA_ACUERDO ADD INCLUYE_TRASLADO VARCHAR (255);
ALTER TABLE Z_RAF_CARTA_ACUERDO ADD INCLUYE_INSCRIPCION VARCHAR (255);
ALTER TABLE Z_RAF_CARTA_ACUERDO ADD SELECCION_ALOJAMIENTO_PRESUPUESTO VARCHAR (255);
ALTER TABLE Z_RAF_CARTA_ACUERDO ADD SELECCION_TRASLADO_PRESUPUESTO VARCHAR (255);
ALTER TABLE Z_RAF_CARTA_ACUERDO ADD SELECCION_INSCRIPCION_PRESUPUESTO VARCHAR (255);